### ISSUE TITLE
build fails for tinystl

### ISSUE THREAD

**Issue by theguly** [rokups/virtual-reality#3]
both using command line and latest clion ide i have this error:

`[ 40%] Building CXX object src/shared/CMakeFiles/shared.dir/coroutine.cpp.obj
In file included from C:\Users\user\Desktop\v\virtual-reality\src\shared\coroutine.h:29:0,
                 from C:\Users\user\Desktop\v\virtual-reality\src\shared\coroutine.cpp:24:
C:/Users/user/Desktop/v/virtual-reality/dep/tinystl/include/stl/function.h:38:59: error: 'is_callable' is not a member of 'std'
     template <class T, typename = typename std::enable_if<std::is_callable<T, Args...>::value>::type>
                                                           ^~~
C:/Users/user/Desktop/v/virtual-reality/dep/tinystl/include/stl/function.h:38:86: error: template argument 1 is invalid
     template <class T, typename = typename std::enable_if<std::is_callable<T, Args...>::value>::type>
                                                                                      ^
C:/Users/user/Desktop/v/virtual-reality/dep/tinystl/include/stl/function.h:38:87: error: expected identifier before '::' token
     template <class T, typename = typename std::enable_if<std::is_callable<T, Args...>::value>::type>
                                                                                       ^~
C:/Users/user/Desktop/v/virtual-reality/dep/tinystl/include/stl/function.h:38:87: error: expected '>' before '::' token
C:/Users/user/Desktop/v/virtual-reality/dep/tinystl/include/stl/function.h:38:97: error: 'type' in namespace '::' does not name a type
     template <class T, typename = typename std::enable_if<std::is_callable<T, Args...>::value>::type>
                                                                                                 ^~~~
C:\Users\user\Desktop\v\virtual-reality\src\shared\coroutine.cpp: In member function 'void coroutine_loop::run()':
C:\Users\user\Desktop\v\virtual-reality\src\shared\coroutine.cpp:87:26: error: 'INT_MAX' was not declared in this scope
         int sleep_time = INT_MAX;
                          ^~~~~~~`

my env is:
Windows 10
latest mingw-w64 downloaded "now"
cmake bundled 3.13.2
make/gcc/g++ from mingw install folder

could you please help debugging this error?

thanks

**Comment by rokups** [comment]
Odd. Error complains about missing `std::is_callable` while [code uses std::is_invocable](https://github.com/rokups/virtual-reality/blob/master/dep/tinystl/include/stl/function.h#L38). Maybe your MingW version does not support that? I tested this code only with MingW that comes with msys2 so if you use any other distribution chances are it may fail.

Edit: I should probably mention that on c++17 they renamed `std::is_callable` to `std::is_invocable`. Maybe that has to do something with this..?

**Comment by theguly** [comment]
that's what happens when you work with 3 different VM open :)
i tried to compile using the "old" function which is is_callable, as also you pointed out. then forgot to revert/save in the right VM before the last compile shot.

by the way, i got it working now: from my tests, it only compiles on msys2 64bit+mingw64, but i can't confirm right now.

thanks for your quick reply and also for this project, back testing.
